name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd my_fastapi_app
            git pull origin main
            docker build -t my_fastapi_app .
            docker stop $(docker ps -q --filter ancestor=my_fastapi_app) || true
            docker run -d -p 8000:8000 my_fastapi_app
